export const data = [
	{
		id: 1,
		color: 'from-cyan-500 to-blue-500',
		title: 'Tails: Shelter for Dogs',
		desc: 'Welcome to our "Tails" dog shelter. We introduce you to our loyal four-legged friends and share their life at the shelter. Technologies Used - TypeScript, React, React Router, Swiper, SCSS, i18next, Tanstack Query, Vitest, Storybook, Vite.',
		img: '/react-tails.jpg',
		code: 'https://github.com/jackal7819/martha-tails',
		link: 'https://martha-tails.onrender.com',
	},
	{
		id: 2,
		color: 'from-cyan-500 to-blue-500',
		title: 'Galaxy Store',
		desc: 'Galaxy Store - the shop where you can find the finest furniture for your comfort and style. Technologies Used - JavaScript, React, React Router, React Toastify, Tailwind CSS, DaisyUI, Tanstack Query, Redux Toolkit, Vite.',
		img: '/react-galaxy.jpg',
		code: 'https://github.com/jackal7819/galaxy-store',
		link: 'https://galaxy-store.onrender.com/',
	},
	{
		id: 3,
		color: 'from-cyan-500 to-blue-500',
		title: 'GitHub Persona',
		desc: `GitHub Persona is a web application that provides information about GitHub users. Users can log in using their GitHub credentials via the login page, view profile data, repositories, programming languages, followers, and starred repositories.`,
		img: '/react-persona.png',
		code: 'https://github.com/jackal7819/github-persona',
		link: 'https://github-persona.onrender.com/',
	},
	{
		id: 4,
		color: 'from-cyan-500 to-blue-500',
		title: 'Gaming Galaxy',
		desc: 'This is a Gaming Galaxy - the best store of Nintendo games. Technologies Used - TypeScript, React, React Router, SCSS, Axios, Redux Toolkit, Webpack.',
		img: '/react-nintendo.jpg',
		code: 'https://github.com/jackal7819/nintendo-store',
		link: 'https://nintendo-store.onrender.com/',
	},
	{
		id: 5,
		color: 'from-cyan-500 to-blue-500',
		title: 'Color Generator',
		desc: 'The Color Generator is a web application that allows you to generate and manage color codes. It provides a user-friendly interface for creating, previewing, and copying color values. Technologies Used - JavaScript, React, React Router, Styled-Components, Tanstack Query, Vite.',
		img: '/react-color.jpg',
		code: 'https://github.com/jackal7819/color-generator',
		link: 'https://color-generator-2a9h.onrender.com/',
	},
	{
		id: 6,
		color: 'from-cyan-500 to-blue-500',
		title: 'CINE World',
		desc: `CINE World is a movie database website built using the TMDB API. It allows users to view information about movies, ratings, what's currently on top. Technologies Used - TypeScript, Next.js, React, Tailwind CSS, TMDB API.`,
		img: '/next-cine.jpg',
		code: 'https://github.com/jackal7819/cine-world',
		link: 'https://imdb-clone-seven-roan.vercel.app/',
	},
	{
		id: 7,
		color: 'from-cyan-500 to-blue-500',
		title: 'Gaming Horizon',
		desc: 'Gaming Horizon - your unique video game store where you can enjoy a wide selection of games, add them to your favorites, create orders, and much more! Technologies Used - JavaScript, Vue.js, Tailwind CSS, Axios, Firebase, Formkit Auto Animate, Vite.',
		img: '/vue-horizon.jpg',
		code: 'https://github.com/jackal7819/gaming-horizon',
		link: 'https://gaming-horizon.onrender.com/',
	},
	{
		id: 8,
		color: 'from-cyan-500 to-blue-500',
		title: 'Pinia Tasks',
		desc: 'Pinia Tasks is a simple task management application. You can add new tasks, delete them, mark them as favorites, display all tasks or only favorites, and also mark tasks as completed. Technologies Used - JavaScript, Vue.js, Tailwind CSS, Axios, Firebase, Nanoid, Vite.',
		img: '/vue-pinia.jpg',
		code: 'https://github.com/jackal7819/pinia-tasks',
		link: 'https://pinia-tasks-c22l.onrender.com/',
	},
	{
		id: 9,
		color: 'from-cyan-500 to-blue-500',
		title: 'Cinematica',
		desc: 'This is a movie application that allows users to browse popular, top-rated, and upcoming movies. The data for movies is fetched from The Movie Database. Technologies Used - JavaScript, Nuxt.js, Vue.js, Tailwind CSS, Axios, Vite, TMDB API.',
		img: '/nuxt-movies.jpg',
		code: 'https://github.com/jackal7819/cinematica',
		link: 'https://cinematica-jade.vercel.app/',
	},
	{
		id: 10,
		color: 'from-cyan-500 to-blue-500',
		title: 'CRM System',
		desc: 'The CRM (Customer Relationship Management) system is a web application that provides a comprehensive solution for managing customer relationships, deals, and sales activities. Technologies Used - TypeScript, Nuxt.js, Vue.js, Pinia, Tailwind CSS, Vue Query, Appwrite, Vite.',
		img: '/nuxt-crm.jpg',
		code: 'https://github.com/jackal7819/crm-system',
		link: 'https://crm-system-nine.vercel.app',
	},
	{
		id: 11,
		color: 'from-cyan-500 to-blue-500',
		title: 'Golden Dragon',
		desc: 'Sushi and rolls delivery application for the Golden Dragon restaurant. Technologies Used - JavaScript, CSS, React, Hooks - useState, useEffect, useContext, useRef, useReducer, Firebase.',
		img: '/react-dragon.png',
		code: 'https://github.com/jackal7819/golden-dragon',
		link: 'https://goldendragon.onrender.com/',
	},
];
