export const data = [
	{
		id: 1,
		color: 'from-cyan-500 to-blue-500',
		title: 'React Commerce',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat.',
		img: '/burger-app.jpg',
		code: 'https://github.com',
		link: 'https://lama.dev',
	},
	{
		id: 2,
		color: 'from-cyan-500 to-blue-500',
		title: 'Next.js Medium Blog',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.',
		img: '/burger-app.jpg',
		code: 'https://github.com',
		link: 'https://lama.dev',
	},
	{
		id: 3,
		color: 'from-cyan-500 to-blue-500',
		title: 'Vanilla Book App',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.',
		img: '/burger-app.jpg',
		code: 'https://github.com',
		link: 'https://lama.dev',
	},
	{
		id: 4,
		color: 'from-cyan-500 to-blue-500',
		title: 'Spotify Music App',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.',
		img: '/burger-app.jpg',
		code: 'https://github.com',
		link: 'https://lama.dev',
	},
	{
		id: 5,
		color: 'from-cyan-500 to-blue-500',
		title: 'Netflix Clone',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.',
		img: '/burger-app.jpg',
		code: 'https://github.com',
		link: 'https://lama.dev',
	},
	{
		id: 6,
		color: 'from-cyan-500 to-blue-500',
		title: 'Youtube Clone',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.',
		img: '/burger-app.jpg',
		code: 'https://github.com',
		link: 'https://lama.dev',
	},
	{
		id: 7,
		color: 'from-cyan-500 to-blue-500',
		title: 'Facebook Clone',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.',
		img: '/burger-app.jpg',
		code: 'https://github.com',
		link: 'https://lama.dev',
	},
	{
		id: 8,
		color: 'from-cyan-500 to-blue-500',
		title: 'Twitter Clone',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.',
		img: '/burger-app.jpg',
		code: 'https://github.com',
		link: 'https://lama.dev',
	},
	{
		id: 9,
		color: 'from-cyan-500 to-blue-500',
		title: 'Instagram Clone',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.',
		img: '/burger-app.jpg',
		code: 'https://github.com',
		link: 'https://lama.dev',
	},
	{
		id: 10,
		color: 'from-cyan-500 to-blue-500',
		title: 'Whatsapp Clone',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.',
		img: '/burger-app.jpg',
		code: 'https://github.com',
		link: 'https://lama.dev',
	},
	{
		id: 11,
		color: 'from-cyan-500 to-blue-500',
		title: 'Spotify Clone',
		desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.',
		img: '/burger-app.jpg',
		code: 'https://github.com',
		link: 'https://lama.dev',
	},
];
