export const data = [
	{
		id: 1,
		color: 'from-cyan-500 to-blue-500',
		title: 'Galaxy Store',
		desc: 'Galaxy Store - the shop where you can find the finest furniture for your comfort and style. Technologies Used - JavaScript, React, React Router, React Toastify, Tailwind CSS, DaisyUI, Tanstack Query, Redux Toolkit, Vite.',
		img: '/react-galaxy.jpg',
		code: 'https://github.com/jackal7819/Galaxy-Store',
		link: 'https://galaxy-store.onrender.com/',
	},
	{
		id: 2,
		color: 'from-cyan-500 to-blue-500',
		title: 'Liquid Lab',
		desc: 'LiquidLab is a SPA designed to introduce users to a delightful collection of cocktail recipes. Technologies Used - JavaScript, React, React Router, React Toastify, Styled-Components, Tanstack Query, Vite, TheCocktailDB API.',
		img: '/react-liquid.jpg',
		code: 'https://github.com/jackal7819/Liquid-Lab',
		link: 'https://liquid-lab.onrender.com/',
	},
	{
		id: 3,
		color: 'from-cyan-500 to-blue-500',
		title: 'Gaming Galaxy',
		desc: 'This is a Gaming Galaxy - the best store of Nintendo games. Technologies Used - TypeScript, React, React Router, SCSS, Axios, Redux Toolkit, Webpack.',
		img: '/react-nintendo.jpg',
		code: 'https://github.com/jackal7819/Nintendo-Store',
		link: 'https://nintendo-store.onrender.com/',
	},
	{
		id: 4,
		color: 'from-cyan-500 to-blue-500',
		title: 'Color Generator',
		desc: 'The Color Generator is a web application that allows you to generate and manage color codes. It provides a user-friendly interface for creating, previewing, and copying color values. Technologies Used - JavaScript, React, React Router, React Toastify, Styled-Components, Tanstack Query, Vite.',
		img: '/react-color.jpg',
		code: 'https://github.com/jackal7819/Color-Generator',
		link: 'https://color-generator-2a9h.onrender.com/',
	},
	{
		id: 5,
		color: 'from-cyan-500 to-blue-500',
		title: 'Metaphor Magic',
		desc: `Metaphor Magic is a full-stack blog application that allows users to create, read, update, and delete blog articles. Technologies Used - JavaScript, React, React Router, React Markdown, MUI, Axios, Redux Toolkit, Webpack, Node.js, Express.js, MongoDB, Mongoose.`,
		img: '/react-blog.jpg',
		code: 'https://github.com/jackal7819/Blog',
		link: 'https://blog-mauve-theta-33.vercel.app/',
	},
	{
		id: 6,
		color: 'from-cyan-500 to-blue-500',
		title: 'CINE World',
		desc: `CINE World is a movie database website built using the TMDB API. It allows users to view information about movies, ratings, what's currently on top. Technologies Used - TypeScript, Next.js, React, Tailwind CSS, TMDB API.`,
		img: '/next-cine.jpg',
		code: 'https://github.com/jackal7819/IMDB-Clone',
		link: 'https://imdb-clone-seven-roan.vercel.app/',
	},
	{
		id: 7,
		color: 'from-cyan-500 to-blue-500',
		title: 'Gaming Horizon',
		desc: 'Gaming Horizon - your unique video game store where you can enjoy a wide selection of games, add them to your favorites, create orders, and much more! Technologies Used - JavaScript, Vue.js, Tailwind CSS, Axios, Firebase, Formkit Auto Animate, Vite.',
		img: '/vue-horizon.jpg',
		code: 'https://github.com/jackal7819/gaming-horizon',
		link: 'https://gaming-horizon.onrender.com/',
	},
	{
		id: 8,
		color: 'from-cyan-500 to-blue-500',
		title: 'Pinia Tasks',
		desc: 'Pinia Tasks is a simple task management application. You can add new tasks, delete them, mark them as favorites, display all tasks or only favorites, and also mark tasks as completed. Technologies Used - JavaScript, Vue.js, Tailwind CSS, Axios, Firebase, Nanoid, Vite.',
		img: '/vue-pinia.jpg',
		code: 'https://github.com/jackal7819/pinia-tasks',
		link: 'https://pinia-tasks-c22l.onrender.com/',
	},
	{
		id: 9,
		color: 'from-cyan-500 to-blue-500',
		title: 'Cinematica',
		desc: 'This is a movie application that allows users to browse popular, top-rated, and upcoming movies. The data for movies is fetched from The Movie Database. Technologies Used - JavaScript, Nuxt.js, Vue.js, Tailwind CSS, Axios, Vite, TMDB API.',
		img: '/nuxt-movies.jpg',
		code: 'https://github.com/jackal7819/cinematica',
		link: 'https://cinematica-jade.vercel.app/',
	},
];
